[package]
name = "multilinear_kzg"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bls12-381 = "0.4.0"
ark-ec = "0.4.2"
ark-ff = "0.4.2"
keccak-rust = "1.0.2"
polynomials = { version = "0.1.0", path = "../polynomials" }
sha2 = "0.10.8"
sha256 = "1.5.0"
