[package]
name = "crypto_primitives"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-bls12-381 = "0.4.0"
ark-bn254 = "0.4.0"
ark-ff = "0.4.2"
ark-poly = "0.4.2"
ark-std = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.111"
sha3 = "0.10.8"


[dev-dependencies]
criterion = "0.5.1"


[[bench]]
name = "univariate_poly"
harness = false

[[bench]]
name = "multilinear_poly"
harness = false
