[package]
name = "reed_solomon_fingerprinting"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-bn254 = "0.4.0"
ark-ff = "0.4.1"
ark-std = "0.4.0"
polynomials = {path = "../polynomials"}
